// Vietnamese cities data
export const CITIES = [
    { value: 'hanoi', label: 'Hà Nội' },
    { value: 'hochiminh', label: 'TP Hồ Chí Minh' },
    { value: 'danang', label: 'Đà Nẵng' },
    { value: 'haiphong', label: 'Hải Phòng' },
    { value: 'cantho', label: 'Cần Thơ' },
    { value: 'binhduong', label: 'Bình Dương' },
    { value: 'dongnai', label: 'Đồng Nai' },
    { value: 'baclieu', label: 'Bạc Liêu' },
    { value: 'bacgiang', label: 'Bắc Giang' },
    { value: 'backan', label: 'Bắc Kạn' },
    { value: 'bacninh', label: 'Bắc Ninh' },
    { value: 'bentre', label: 'Bến Tre' },
    { value: 'binhdinh', label: 'Bình Định' },
    { value: 'binhphuoc', label: 'Bình Phước' },
    { value: 'binhthuan', label: 'Bình Thuận' },
    { value: 'camau', label: 'Cà Mau' },
    { value: 'caobang', label: 'Cao Bằng' },
    { value: 'daklak', label: 'Đắk Lắk' },
    { value: 'daknong', label: 'Đắk Nông' },
    { value: 'dienbien', label: 'Điện Biên' },
    { value: 'dongtháp', label: 'Đồng Tháp' },
    { value: 'gialai', label: 'Gia Lai' },
    { value: 'hagiang', label: 'Hà Giang' },
    { value: 'hanam', label: 'Hà Nam' },
    { value: 'hatinh', label: 'Hà Tĩnh' },
    { value: 'haugiang', label: 'Hậu Giang' },
    { value: 'hoabinh', label: 'Hòa Bình' },
    { value: 'hungyen', label: 'Hưng Yên' },
    { value: 'khanhhoa', label: 'Khánh Hòa' },
    { value: 'kiengiang', label: 'Kiên Giang' },
    { value: 'kontum', label: 'Kon Tum' },
    { value: 'laichau', label: 'Lai Châu' },
    { value: 'lamdong', label: 'Lâm Đồng' },
    { value: 'langson', label: 'Lạng Sơn' },
    { value: 'laocai', label: 'Lào Cai' },
    { value: 'longan', label: 'Long An' },
    { value: 'namdinh', label: 'Nam Định' },
    { value: 'nghean', label: 'Nghệ An' },
    { value: 'ninhbinh', label: 'Ninh Bình' },
    { value: 'ninhthuan', label: 'Ninh Thuận' },
    { value: 'phutho', label: 'Phú Thọ' },
    { value: 'phuyen', label: 'Phú Yên' },
    { value: 'quangbinh', label: 'Quảng Bình' },
    { value: 'quangnam', label: 'Quảng Nam' },
    { value: 'quangngai', label: 'Quảng Ngãi' },
    { value: 'quangninh', label: 'Quảng Ninh' },
    { value: 'quangtri', label: 'Quảng Trị' },
    { value: 'soctrang', label: 'Sóc Trăng' },
    { value: 'sonla', label: 'Sơn La' },
    { value: 'tayninh', label: 'Tây Ninh' },
    { value: 'thaibinh', label: 'Thái Bình' },
    { value: 'thainguyen', label: 'Thái Nguyên' },
    { value: 'thanhhoa', label: 'Thanh Hóa' },
    { value: 'thuathienhue', label: 'Thừa Thiên Huế' },
    { value: 'tiengiang', label: 'Tiền Giang' },
    { value: 'travinh', label: 'Trà Vinh' },
    { value: 'tuyenquang', label: 'Tuyên Quang' },
    { value: 'vinhlong', label: 'Vĩnh Long' },
    { value: 'vinhphuc', label: 'Vĩnh Phúc' },
    { value: 'yenbai', label: 'Yên Bái' },
];

// Districts by city
export const DISTRICTS: Record<string, { value: string; label: string }[]> = {
    hanoi: [
        { value: 'badinh', label: 'Ba Đình' },
        { value: 'hoankien', label: 'Hoàn Kiếm' },
        { value: 'tayho', label: 'Tây Hồ' },
        { value: 'longsien', label: 'Long Biên' },
        { value: 'caugiay', label: 'Cầu Giấy' },
        { value: 'dongda', label: 'Đống Đa' },
        { value: 'haibatrung', label: 'Hai Bà Trưng' },
        { value: 'hoangmai', label: 'Hoàng Mai' },
        { value: 'thanhxuan', label: 'Thanh Xuân' },
        { value: 'namtukiem', label: 'Nam Từ Liêm' },
        { value: 'bactukiem', label: 'Bắc Từ Liêm' },
        { value: 'hadong', label: 'Hà Đông' },
    ],
    hochiminh: [
        { value: 'quan1', label: 'Quận 1' },
        { value: 'quan2', label: 'Quận 2' },
        { value: 'quan3', label: 'Quận 3' },
        { value: 'quan4', label: 'Quận 4' },
        { value: 'quan5', label: 'Quận 5' },
        { value: 'quan6', label: 'Quận 6' },
        { value: 'quan7', label: 'Quận 7' },
        { value: 'quan8', label: 'Quận 8' },
        { value: 'quan9', label: 'Quận 9' },
        { value: 'quan10', label: 'Quận 10' },
        { value: 'quan11', label: 'Quận 11' },
        { value: 'quan12', label: 'Quận 12' },
        { value: 'binhtan', label: 'Bình Tân' },
        { value: 'binhthanh', label: 'Bình Thạnh' },
        { value: 'govap', label: 'Gò Vấp' },
        { value: 'phunhuan', label: 'Phú Nhuận' },
        { value: 'tanbinh', label: 'Tân Bình' },
        { value: 'tanphu', label: 'Tân Phú' },
        { value: 'thuduc', label: 'Thủ Đức' },
    ],
    danang: [
        { value: 'haichau', label: 'Hải Châu' },
        { value: 'thanhkhe', label: 'Thanh Khê' },
        { value: 'sontra', label: 'Sơn Trà' },
        { value: 'nguhanh', label: 'Ngũ Hành Sơn' },
        { value: 'lienchieo', label: 'Liên Chiểu' },
        { value: 'camle', label: 'Cẩm Lệ' },
    ],
    // Add default for other cities
    default: [
        { value: 'central', label: 'Trung tâm' },
        { value: 'suburban', label: 'Ngoại thành' },
    ],
};
